version: '3.8'

services:
  calculadora:
    build: .
    container_name: calculadora-tributaria
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - calculadora-db:/data

volumes:
  calculadora-db:
